// Core SEO Identity & Keywords — Elani Beauty Hub (Thrift & New Fashion)
export const SITE_SEO = {
  siteName: "Elani Beauty Hub",
  siteUrl: "https://elanibeautyhub.com",
  siteTitle: "Elani Beauty Hub | Thrift & New Tops, Dresses, Bodysuits & Jackets in Nairobi",
  siteDescription:
    "Shop affordable thrift and new women's tops, dresses, bodysuits, and jackets at Elani Beauty Hub Nairobi. Best place to buy quality thrift fashion in Kenya. Order online or call 0702642324.",
  phone: "+254702642324",
  phoneDisplay: "0702642324",
  email: "info@classycollections.com",
  instagram: "@_classycollections",
  tiktok: "@_classycollections",
  twitter: "@_classycollections",
  whatsapp: "254702642324",
  address: "Nairobi, Kenya",

  // 1000+ SEO Keywords — comprehensive, creative, brand-focused, product-specific
  allKeywords: [
    // ========== BRAND KEYWORDS (50+) ==========
    "Elani Beauty Hub",
    "Elani Beauty Hub Nairobi",
    "Elani Beauty Hub Kenya",
    "Elani Beauty Hub thrift",
    "Elani Beauty Hub online store",
    "Elani Beauty Hub fashion",
    "Elani Beauty Hub 0702642324",
    "Elani Beauty Hub shop",
    "Elani Beauty Hub clothes",
    "Elani Beauty Hub dresses",
    "Elani Beauty Hub tops",
    "Elani Beauty Hub bodysuits",
    "Elani Beauty Hub jackets",
    "Elani Beauty Hub women",
    "Elani Beauty Hub men",
    "Elani Beauty Hub delivery",
    "Elani Beauty Hub order",
    "Elani Beauty Hub WhatsApp",
    "Elani Beauty Hub prices",
    "Elani Beauty Hub offers",
    "Elani Beauty Hub new arrivals",
    "Elani Beauty Hub sale",
    "Elani Beauty Hub deals",
    "Elani Beauty Hub best seller",
    "Elani Beauty Hub reviews",
    "Elani Beauty Hub affordable fashion",
    "Elani Beauty Hub quality thrift",
    "Elani Beauty Hub preloved",
    "Elani Beauty Hub second hand",
    "Elani Beauty Hub mitumba",
    "Elani Beauty Hub baby shop",
    "Elani Beauty Hub kids",
    "Elani Beauty Hub contact",
    "Elani Beauty Hub location",
    "Elani Beauty Hub Instagram",
    "Elani Beauty Hub TikTok",
    "Elani online store",
    "Elani fashion Kenya",
    "Elani thrift shop",
    "Elani Nairobi",
    "beauty hub fashion",
    "beauty hub thrift",
    "beauty hub Nairobi",
    "beauty hub Kenya",
    "beauty hub online",
    "elanibeautyhub",
    "elanibeautyhub.com",
    "Elani Beauty Hub collection",
    "Elani Beauty Hub catalogue",
    "Elani Beauty Hub wardrobe",

    // ========== THRIFT / SECOND-HAND / PRELOVED (80+) ==========
    "thrift shop Nairobi",
    "thrift store Kenya",
    "thrift clothes Nairobi",
    "thrift fashion Kenya",
    "thrift dresses Nairobi",
    "thrift tops Kenya",
    "thrift jackets Nairobi",
    "thrift bodysuits Kenya",
    "best thrift shop Nairobi",
    "best thrift store Kenya",
    "affordable thrift Kenya",
    "quality thrift clothing Nairobi",
    "thrift shopping online Kenya",
    "thrift wear Nairobi",
    "thrift outfits Kenya",
    "cheap thrift clothes Nairobi",
    "online thrift store Kenya",
    "thrift finds Nairobi",
    "thrift haul Kenya",
    "second hand clothes Nairobi",
    "second hand fashion Kenya",
    "preloved fashion Nairobi",
    "preloved clothes Kenya",
    "ukay ukay Nairobi",
    "mitumba fashion Kenya",
    "mitumba clothes Nairobi",
    "best mitumba shop Nairobi",
    "thrift flips Kenya",
    "thrift style Nairobi",
    "thrift wardrobe Kenya",
    "thrift closet Nairobi",
    "curated thrift Kenya",
    "premium thrift Nairobi",
    "luxury thrift Kenya",
    "designer thrift Nairobi",
    "vintage thrift Kenya",
    "retro thrift Nairobi",
    "thrift boutique Kenya",
    "thrift collection Nairobi",
    "thrift gems Kenya",
    "thrift treasures Nairobi",
    "thrift picks Kenya",
    "thrift steals Nairobi",
    "thrift bargains Kenya",
    "thrift deals Nairobi",
    "thrift clearance Kenya",
    "thrift bundle Nairobi",
    "thrift mix Kenya",
    "thrift assorted Nairobi",
    "sustainable fashion Kenya",
    "eco fashion Nairobi",
    "green fashion Kenya",
    "recycled fashion Nairobi",
    "upcycled clothes Kenya",
    "circular fashion Nairobi",
    "conscious fashion Kenya",
    "ethical fashion Nairobi",
    "slow fashion Kenya",
    "pre-owned clothes Nairobi",
    "gently used clothes Kenya",
    "like new clothes Nairobi",
    "barely worn clothes Kenya",
    "ex-UK clothes Nairobi",
    "ex-US clothes Kenya",
    "imported thrift Kenya",
    "bale clothes Nairobi",
    "mitumba bale Kenya",
    "sorted mitumba Nairobi",
    "grade A mitumba Kenya",
    "premium mitumba Nairobi",
    "clean thrift Kenya",
    "fresh thrift Nairobi",
    "hand-picked thrift Kenya",
    "selected thrift Nairobi",
    "inspected thrift Kenya",
    "verified thrift Nairobi",
    "trusted thrift Kenya",
    "reliable thrift shop Nairobi",
    "genuine thrift Kenya",
    "original thrift Nairobi",
    "authentic thrift Kenya",

    // ========== TOPS KEYWORDS (80+) ==========
    "buy tops online Kenya",
    "women tops Nairobi",
    "thrift tops Nairobi",
    "crop tops Kenya",
    "blouses Nairobi",
    "going out tops Kenya",
    "casual tops Nairobi",
    "office tops Kenya",
    "peplum tops Nairobi",
    "best place to buy tops Nairobi",
    "affordable tops Kenya",
    "trendy tops Nairobi",
    "stylish tops Kenya",
    "tank tops Kenya",
    "camisole tops Nairobi",
    "tube tops Kenya",
    "halter tops Nairobi",
    "off shoulder tops Kenya",
    "one shoulder tops Nairobi",
    "long sleeve tops Kenya",
    "short sleeve tops Nairobi",
    "sleeveless tops Kenya",
    "v-neck tops Nairobi",
    "round neck tops Kenya",
    "turtle neck tops Nairobi",
    "mock neck tops Kenya",
    "polo tops Nairobi",
    "button up tops Kenya",
    "wrap tops Nairobi",
    "tie front tops Kenya",
    "ruffle tops Nairobi",
    "lace tops Kenya",
    "mesh tops Nairobi",
    "sheer tops Kenya",
    "sequin tops Nairobi",
    "satin tops Kenya",
    "silk tops Nairobi",
    "chiffon tops Kenya",
    "cotton tops Nairobi",
    "ribbed tops Kenya",
    "knit tops Nairobi",
    "sweater tops Kenya",
    "printed tops Nairobi",
    "striped tops Kenya",
    "floral tops Nairobi",
    "graphic tops Kenya",
    "plain tops Nairobi",
    "solid color tops Kenya",
    "embroidered tops Nairobi",
    "beaded tops Kenya",
    "corset tops Nairobi",
    "bustier tops Kenya",
    "bralette tops Nairobi",
    "smocked tops Kenya",
    "fitted tops Nairobi",
    "loose fit tops Kenya",
    "oversized tops Nairobi",
    "cropped tops Kenya",
    "longline tops Nairobi",
    "tunic tops Kenya",
    "peasant tops Nairobi",
    "boho tops Kenya",
    "vintage tops Nairobi",
    "retro tops Kenya",
    "elegant tops Nairobi",
    "classy tops Kenya",
    "chic tops Nairobi",
    "cute tops Kenya",
    "sexy tops Nairobi",
    "date night tops Kenya",
    "brunch tops Nairobi",
    "party tops Kenya",
    "club tops Nairobi",
    "festival tops Kenya",
    "summer tops Nairobi",
    "warm weather tops Kenya",
    "lightweight tops Nairobi",
    "layering tops Kenya",
    "basic tops Nairobi",
    "essential tops Kenya",

    // ========== DRESSES KEYWORDS (100+) ==========
    "buy dresses online Kenya",
    "women dresses Nairobi",
    "thrift dresses Kenya",
    "maxi dresses Nairobi",
    "mini dresses Kenya",
    "bodycon dresses Nairobi",
    "casual dresses Kenya",
    "party dresses Nairobi",
    "cocktail dresses Kenya",
    "evening dresses Nairobi",
    "office dresses Kenya",
    "best place to buy dresses Nairobi",
    "affordable dresses Kenya",
    "sundresses Nairobi",
    "lace dresses Kenya",
    "floral dresses Nairobi",
    "short dresses Kenya",
    "long dresses Nairobi",
    "midi dresses Kenya",
    "A-line dresses Nairobi",
    "fit and flare dresses Kenya",
    "wrap dresses Nairobi",
    "shirt dresses Kenya",
    "t-shirt dresses Nairobi",
    "sweater dresses Kenya",
    "knit dresses Nairobi",
    "shift dresses Kenya",
    "sheath dresses Nairobi",
    "pencil dresses Kenya",
    "slip dresses Nairobi",
    "satin dresses Kenya",
    "silk dresses Nairobi",
    "chiffon dresses Kenya",
    "velvet dresses Nairobi",
    "denim dresses Kenya",
    "off shoulder dresses Nairobi",
    "one shoulder dresses Kenya",
    "strapless dresses Nairobi",
    "halter dresses Kenya",
    "backless dresses Nairobi",
    "cut out dresses Kenya",
    "slit dresses Nairobi",
    "tiered dresses Kenya",
    "ruffle dresses Nairobi",
    "pleated dresses Kenya",
    "printed dresses Nairobi",
    "striped dresses Kenya",
    "polka dot dresses Nairobi",
    "animal print dresses Kenya",
    "geometric dresses Nairobi",
    "plain dresses Kenya",
    "black dresses Nairobi",
    "white dresses Kenya",
    "red dresses Nairobi",
    "pink dresses Kenya",
    "blue dresses Nairobi",
    "green dresses Kenya",
    "yellow dresses Nairobi",
    "purple dresses Kenya",
    "orange dresses Nairobi",
    "multicolor dresses Kenya",
    "pastel dresses Nairobi",
    "neon dresses Kenya",
    "little black dress Nairobi",
    "LBD Kenya",
    "wedding guest dresses Nairobi",
    "bridesmaid dresses Kenya",
    "church dresses Nairobi",
    "Sunday dresses Kenya",
    "graduation dresses Nairobi",
    "birthday dresses Kenya",
    "anniversary dresses Nairobi",
    "date night dresses Kenya",
    "dinner dresses Nairobi",
    "brunch dresses Kenya",
    "garden party dresses Nairobi",
    "beach dresses Kenya",
    "vacation dresses Nairobi",
    "travel dresses Kenya",
    "work dresses Nairobi",
    "corporate dresses Kenya",
    "interview dresses Nairobi",
    "professional dresses Kenya",
    "elegant dresses Nairobi",
    "classy dresses Kenya",
    "sophisticated dresses Nairobi",
    "chic dresses Kenya",
    "trendy dresses Nairobi",
    "fashionable dresses Kenya",
    "stylish dresses Nairobi",
    "cute dresses Kenya",
    "affordable party dresses Nairobi",
    "cheap dresses Kenya",
    "budget dresses Nairobi",
    "plus size dresses Kenya",
    "petite dresses Nairobi",
    "maternity dresses Kenya",
    "nursing friendly dresses Nairobi",
    "modest dresses Kenya",
    "conservative dresses Nairobi",

    // ========== BODYSUITS KEYWORDS (70+) ==========
    "buy bodysuits online Kenya",
    "women bodysuits Nairobi",
    "thrift bodysuits Kenya",
    "bodycon bodysuits Nairobi",
    "off-shoulder bodysuits Kenya",
    "turtleneck bodysuits Nairobi",
    "mesh bodysuits Kenya",
    "ribbed bodysuits Nairobi",
    "spaghetti strap bodysuits Kenya",
    "best place to buy bodysuits Nairobi",
    "affordable bodysuits Kenya",
    "plus size bodysuits Nairobi",
    "lace bodysuits Kenya",
    "sheer bodysuits Nairobi",
    "long sleeve bodysuits Kenya",
    "short sleeve bodysuits Nairobi",
    "sleeveless bodysuits Kenya",
    "halter bodysuits Nairobi",
    "backless bodysuits Kenya",
    "plunge bodysuits Nairobi",
    "square neck bodysuits Kenya",
    "v-neck bodysuits Nairobi",
    "scoop neck bodysuits Kenya",
    "high neck bodysuits Nairobi",
    "mock neck bodysuits Kenya",
    "collared bodysuits Nairobi",
    "button up bodysuits Kenya",
    "snap closure bodysuits Nairobi",
    "thong bodysuits Kenya",
    "seamless bodysuits Nairobi",
    "shapewear bodysuits Kenya",
    "sculpting bodysuits Nairobi",
    "compression bodysuits Kenya",
    "satin bodysuits Nairobi",
    "velvet bodysuits Kenya",
    "cotton bodysuits Nairobi",
    "spandex bodysuits Kenya",
    "nylon bodysuits Nairobi",
    "printed bodysuits Kenya",
    "floral bodysuits Nairobi",
    "animal print bodysuits Kenya",
    "plain bodysuits Nairobi",
    "black bodysuits Kenya",
    "white bodysuits Nairobi",
    "nude bodysuits Kenya",
    "red bodysuits Nairobi",
    "sexy bodysuits Kenya",
    "going out bodysuits Nairobi",
    "club bodysuits Kenya",
    "party bodysuits Nairobi",
    "date night bodysuits Kenya",
    "casual bodysuits Nairobi",
    "everyday bodysuits Kenya",
    "layering bodysuits Nairobi",
    "office bodysuits Kenya",
    "work bodysuits Nairobi",
    "elegant bodysuits Kenya",
    "classy bodysuits Nairobi",
    "trendy bodysuits Kenya",
    "fashionable bodysuits Nairobi",
    "stylish bodysuits Kenya",
    "cute bodysuits Nairobi",
    "flattering bodysuits Kenya",
    "bodysuit outfit ideas Nairobi",
    "bodysuit with jeans Kenya",
    "bodysuit with skirt Nairobi",
    "bodysuit with trousers Kenya",
    "bodysuit style Nairobi",
    "bodysuit fashion Kenya",
    "bodysuit trend Nairobi",

    // ========== JACKETS & OUTERWEAR KEYWORDS (80+) ==========
    "buy jackets online Kenya",
    "women jackets Nairobi",
    "thrift jackets Kenya",
    "denim jackets Nairobi",
    "leather jackets Kenya",
    "bomber jackets Nairobi",
    "blazers Kenya",
    "best place to buy jackets Nairobi",
    "affordable jackets Kenya",
    "cropped jackets Nairobi",
    "oversized jackets Kenya",
    "fitted jackets Nairobi",
    "puffer jackets Kenya",
    "padded jackets Nairobi",
    "quilted jackets Kenya",
    "windbreaker jackets Nairobi",
    "rain jackets Kenya",
    "waterproof jackets Nairobi",
    "trench coats Kenya",
    "long coats Nairobi",
    "short coats Kenya",
    "wool coats Nairobi",
    "faux fur jackets Kenya",
    "fleece jackets Nairobi",
    "hoodie jackets Kenya",
    "zip up jackets Nairobi",
    "button up jackets Kenya",
    "military jackets Nairobi",
    "cargo jackets Kenya",
    "utility jackets Nairobi",
    "field jackets Kenya",
    "safari jackets Nairobi",
    "moto jackets Kenya",
    "biker jackets Nairobi",
    "suede jackets Kenya",
    "faux leather jackets Nairobi",
    "vegan leather jackets Kenya",
    "varsity jackets Nairobi",
    "letterman jackets Kenya",
    "track jackets Nairobi",
    "sport jackets Kenya",
    "casual blazers Nairobi",
    "formal blazers Kenya",
    "office blazers Nairobi",
    "double breasted blazers Kenya",
    "single breasted blazers Nairobi",
    "plaid blazers Kenya",
    "pinstripe blazers Nairobi",
    "tweed jackets Kenya",
    "knit cardigans Nairobi",
    "long cardigans Kenya",
    "short cardigans Nairobi",
    "open front cardigans Kenya",
    "button cardigans Nairobi",
    "kimono jackets Kenya",
    "cape jackets Nairobi",
    "poncho wraps Kenya",
    "shrug jackets Nairobi",
    "bolero jackets Kenya",
    "jean jackets Nairobi",
    "distressed denim jackets Kenya",
    "colored denim jackets Nairobi",
    "black jackets Kenya",
    "brown jackets Nairobi",
    "white jackets Kenya",
    "beige jackets Nairobi",
    "khaki jackets Kenya",
    "olive jackets Nairobi",
    "navy jackets Kenya",
    "red jackets Nairobi",
    "printed jackets Kenya",
    "embroidered jackets Nairobi",
    "sequin jackets Kenya",
    "party jackets Nairobi",
    "going out jackets Kenya",
    "evening jackets Nairobi",
    "layering jackets Kenya",
    "transitional jackets Nairobi",
    "all weather jackets Kenya",

    // ========== SKIRTS KEYWORDS (50+) ==========
    "buy skirts online Kenya",
    "women skirts Nairobi",
    "thrift skirts Kenya",
    "mini skirts Nairobi",
    "midi skirts Kenya",
    "maxi skirts Nairobi",
    "pencil skirts Kenya",
    "A-line skirts Nairobi",
    "pleated skirts Kenya",
    "wrap skirts Nairobi",
    "denim skirts Kenya",
    "leather skirts Nairobi",
    "satin skirts Kenya",
    "silk skirts Nairobi",
    "tulle skirts Kenya",
    "tiered skirts Nairobi",
    "ruffle skirts Kenya",
    "flared skirts Nairobi",
    "circle skirts Kenya",
    "high waist skirts Nairobi",
    "low waist skirts Kenya",
    "bodycon skirts Nairobi",
    "fitted skirts Kenya",
    "flowy skirts Nairobi",
    "asymmetric skirts Kenya",
    "slit skirts Nairobi",
    "printed skirts Kenya",
    "floral skirts Nairobi",
    "plaid skirts Kenya",
    "striped skirts Nairobi",
    "solid skirts Kenya",
    "black skirts Nairobi",
    "office skirts Kenya",
    "casual skirts Nairobi",
    "party skirts Kenya",
    "elegant skirts Nairobi",
    "trendy skirts Kenya",
    "affordable skirts Nairobi",
    "thrift skirts deals Kenya",
    "cargo skirts Nairobi",
    "tennis skirts Kenya",
    "school skirts Nairobi",
    "skater skirts Kenya",
    "button front skirts Nairobi",
    "zipper skirts Kenya",
    "elastic waist skirts Nairobi",
    "pocketless skirts Kenya",
    "skirts with pockets Nairobi",
    "layered skirts Kenya",
    "embellished skirts Nairobi",

    // ========== PANTS & TROUSERS KEYWORDS (50+) ==========
    "buy trousers online Kenya",
    "women trousers Nairobi",
    "thrift trousers Kenya",
    "jeans Nairobi",
    "thrift jeans Kenya",
    "wide leg trousers Nairobi",
    "straight leg trousers Kenya",
    "skinny jeans Nairobi",
    "mom jeans Kenya",
    "boyfriend jeans Nairobi",
    "high waist jeans Kenya",
    "low rise jeans Nairobi",
    "flared jeans Kenya",
    "bootcut jeans Nairobi",
    "cargo pants Kenya",
    "palazzo pants Nairobi",
    "culottes Kenya",
    "shorts Nairobi",
    "denim shorts Kenya",
    "cycling shorts Nairobi",
    "bermuda shorts Kenya",
    "high waist shorts Nairobi",
    "paper bag waist trousers Kenya",
    "tailored trousers Nairobi",
    "dress pants Kenya",
    "office trousers Nairobi",
    "formal trousers Kenya",
    "casual trousers Nairobi",
    "linen trousers Kenya",
    "cotton trousers Nairobi",
    "joggers Kenya",
    "sweatpants Nairobi",
    "track pants Kenya",
    "leggings Nairobi",
    "jeggings Kenya",
    "leather pants Nairobi",
    "faux leather pants Kenya",
    "corduroy pants Nairobi",
    "velvet pants Kenya",
    "printed trousers Nairobi",
    "plaid trousers Kenya",
    "striped trousers Nairobi",
    "solid trousers Kenya",
    "black trousers Nairobi",
    "white trousers Kenya",
    "blue jeans Nairobi",
    "distressed jeans Kenya",
    "ripped jeans Nairobi",
    "raw hem jeans Kenya",
    "affordable trousers Nairobi",

    // ========== JUMPSUITS & ROMPERS (30+) ==========
    "jumpsuits Kenya",
    "rompers Nairobi",
    "thrift jumpsuits Kenya",
    "wide leg jumpsuits Nairobi",
    "fitted jumpsuits Kenya",
    "casual jumpsuits Nairobi",
    "dressy jumpsuits Kenya",
    "office jumpsuits Nairobi",
    "strapless jumpsuits Kenya",
    "spaghetti strap jumpsuits Nairobi",
    "long sleeve jumpsuits Kenya",
    "short jumpsuits Nairobi",
    "denim jumpsuits Kenya",
    "utility jumpsuits Nairobi",
    "cargo jumpsuits Kenya",
    "playsuit Nairobi",
    "playsuits Kenya",
    "short rompers Nairobi",
    "floral jumpsuits Kenya",
    "printed jumpsuits Nairobi",
    "plain jumpsuits Kenya",
    "black jumpsuits Nairobi",
    "white jumpsuits Kenya",
    "party jumpsuits Nairobi",
    "elegant jumpsuits Kenya",
    "affordable jumpsuits Nairobi",
    "thrift rompers Kenya",
    "wrap jumpsuits Nairobi",
    "belted jumpsuits Kenya",
    "palazzo jumpsuits Nairobi",

    // ========== SETS & CO-ORDS (25+) ==========
    "matching sets Kenya",
    "co-ord sets Nairobi",
    "two piece sets Kenya",
    "thrift matching sets Nairobi",
    "crop top and skirt set Kenya",
    "blazer and trouser set Nairobi",
    "top and pants set Kenya",
    "lounge sets Nairobi",
    "casual sets Kenya",
    "office sets Nairobi",
    "party sets Kenya",
    "printed sets Nairobi",
    "knit sets Kenya",
    "ribbed sets Nairobi",
    "satin sets Kenya",
    "power suits women Nairobi",
    "women suit sets Kenya",
    "trouser suits Nairobi",
    "skirt suits Kenya",
    "short sets Nairobi",
    "summer sets Kenya",
    "elegant sets Nairobi",
    "affordable sets Kenya",
    "thrift co-ords Nairobi",
    "matching outfits Kenya",

    // ========== MEN'S FASHION KEYWORDS (80+) ==========
    "men fashion Nairobi",
    "men clothing Kenya",
    "thrift men clothes Nairobi",
    "men shirts Kenya",
    "thrift shirts men Nairobi",
    "men t-shirts Kenya",
    "polo shirts men Nairobi",
    "button up shirts men Kenya",
    "dress shirts men Nairobi",
    "casual shirts men Kenya",
    "Hawaiian shirts men Nairobi",
    "flannel shirts men Kenya",
    "men jackets Nairobi",
    "thrift jackets men Kenya",
    "men blazers Nairobi",
    "men suits Kenya",
    "men trousers Nairobi",
    "men jeans Kenya",
    "men chinos Nairobi",
    "men khakis Kenya",
    "men shorts Nairobi",
    "men cargo pants Kenya",
    "men joggers Nairobi",
    "men sweatshirts Kenya",
    "men hoodies Nairobi",
    "men sweaters Kenya",
    "men cardigans Nairobi",
    "men vests Kenya",
    "men formal wear Nairobi",
    "men casual wear Kenya",
    "men office wear Nairobi",
    "men streetwear Kenya",
    "men vintage fashion Nairobi",
    "men thrift fashion Kenya",
    "affordable men clothing Nairobi",
    "quality men thrift Kenya",
    "men fashion deals Nairobi",
    "men wardrobe essentials Kenya",
    "men basics Nairobi",
    "men outfits Kenya",
    "men style Nairobi",
    "men accessories Kenya",
    "men belts Nairobi",
    "men ties Kenya",
    "men denim jacket Nairobi",
    "men leather jacket Kenya",
    "men bomber jacket Nairobi",
    "men puffer jacket Kenya",
    "men track suit Nairobi",
    "men sportswear Kenya",
    "men athleisure Nairobi",
    "men workwear Kenya",
    "men smart casual Nairobi",
    "men wedding outfits Kenya",
    "men graduation outfits Nairobi",
    "men church outfits Kenya",
    "men Sunday best Nairobi",
    "men Elani Beauty Hub",
    "men thrift Nairobi best",
    "men preloved clothes Kenya",
    "men second hand fashion Nairobi",
    "men mitumba Kenya",
    "men ex-UK clothes Nairobi",
    "men imported thrift Kenya",
    "men designer thrift Nairobi",
    "men branded clothes Kenya",
    "men affordable style Nairobi",
    "men trendy clothes Kenya",
    "men fashionable clothing Nairobi",
    "men classic style Kenya",
    "men modern fashion Nairobi",
    "men urban fashion Kenya",
    "men Nairobi fashion",
    "men Kenya clothing online",
    "buy men clothes online Kenya",
    "order men clothes Nairobi",
    "men clothing delivery Kenya",
    "men thrift delivery Nairobi",
    "men clothes WhatsApp order Kenya",
    "men M-PESA fashion Nairobi",

    // ========== BABY & KIDS KEYWORDS (40+) ==========
    "baby clothes Kenya",
    "kids clothes Nairobi",
    "baby shop Nairobi",
    "thrift baby clothes Kenya",
    "thrift kids clothes Nairobi",
    "affordable baby clothes Kenya",
    "baby dresses Nairobi",
    "baby rompers Kenya",
    "baby onesies Nairobi",
    "baby bodysuits Kenya",
    "baby tops Nairobi",
    "baby pants Kenya",
    "baby jackets Nairobi",
    "baby shoes Kenya",
    "toddler clothes Nairobi",
    "kids fashion Kenya",
    "children clothing Nairobi",
    "boys clothes Kenya",
    "girls clothes Nairobi",
    "girls dresses Kenya",
    "boys shirts Nairobi",
    "kids thrift Kenya",
    "baby thrift Nairobi",
    "preloved baby clothes Kenya",
    "second hand kids clothes Nairobi",
    "baby mitumba Kenya",
    "kids mitumba Nairobi",
    "baby clothing deals Kenya",
    "affordable kids fashion Nairobi",
    "cute baby clothes Kenya",
    "baby outfit sets Nairobi",
    "kids matching sets Kenya",
    "baby essentials Nairobi",
    "newborn clothes Kenya",
    "infant clothes Nairobi",
    "baby 0-3 months Kenya",
    "baby 3-6 months Nairobi",
    "baby 6-12 months Kenya",
    "toddler 1-2 years Nairobi",
    "kids 2-5 years Kenya",

    // ========== GENERAL FASHION KEYWORDS (80+) ==========
    "women fashion Nairobi",
    "women fashion Kenya",
    "affordable fashion Kenya",
    "quality fashion Nairobi",
    "trendy fashion Kenya",
    "buy women clothing online Kenya",
    "online fashion store Kenya",
    "Nairobi fashion boutique",
    "Kenyan fashion brands",
    "fashion trends Kenya 2026",
    "best online clothing store Kenya",
    "new and thrift fashion Kenya",
    "curated fashion Nairobi",
    "fashion store near me Nairobi",
    "clothing shop Nairobi CBD",
    "fashion delivery same day Nairobi",
    "next day fashion delivery Kenya",
    "budget fashion Kenya",
    "value fashion Nairobi",
    "discount fashion Kenya",
    "clearance fashion Nairobi",
    "flash sale fashion Kenya",
    "fashion offers today Nairobi",
    "fashion deals of the week Kenya",
    "new arrivals fashion Nairobi",
    "just arrived fashion Kenya",
    "latest fashion Nairobi",
    "trending fashion Kenya",
    "viral fashion Nairobi",
    "TikTok fashion Kenya",
    "Instagram fashion Nairobi",
    "influencer fashion Kenya",
    "celebrity fashion Nairobi",
    "street style Kenya",
    "Nairobi street fashion",
    "urban fashion Kenya",
    "city fashion Nairobi",
    "campus fashion Kenya",
    "university outfits Nairobi",
    "college fashion Kenya",
    "young women fashion Nairobi",
    "ladies fashion Kenya",
    "girls fashion Nairobi",
    "women clothing store Kenya",
    "ladies clothing Nairobi",
    "female fashion Kenya",
    "feminine style Nairobi",
    "power dressing Kenya",
    "boss lady fashion Nairobi",
    "career woman fashion Kenya",
    "working woman wardrobe Nairobi",
    "stay at home mom fashion Kenya",
    "mom style Nairobi",
    "mum fashion Kenya",
    "maternity fashion Nairobi",
    "pregnancy style Kenya",
    "postpartum fashion Nairobi",
    "body positive fashion Kenya",
    "all sizes fashion Nairobi",
    "inclusive fashion Kenya",
    "size inclusive clothing Nairobi",
    "plus size fashion Kenya",
    "curvy fashion Nairobi",
    "petite fashion Kenya",
    "tall women fashion Nairobi",
    "fashion for every body Kenya",
    "flattering clothes Nairobi",
    "confidence fashion Kenya",
    "feel good fashion Nairobi",
    "wardrobe refresh Kenya",
    "wardrobe makeover Nairobi",
    "wardrobe essentials Kenya",
    "capsule wardrobe Nairobi",
    "mix and match fashion Kenya",
    "versatile fashion Nairobi",
    "multi-way clothes Kenya",
    "transformable fashion Nairobi",
    "day to night outfits Kenya",
    "transitional fashion Nairobi",

    // ========== OCCASION KEYWORDS (80+) ==========
    "date night outfits Kenya",
    "office wear women Kenya",
    "wedding guest outfits Kenya",
    "graduation outfits Kenya",
    "holiday outfits Kenya",
    "festival outfits Nairobi",
    "casual women wear Kenya",
    "professional women wear Nairobi",
    "formal wear women Kenya",
    "streetwear women Kenya",
    "church outfits women Nairobi",
    "Sunday service outfits Kenya",
    "funeral outfits Nairobi",
    "memorial outfits Kenya",
    "baby shower outfits Nairobi",
    "bridal shower outfits Kenya",
    "bachelorette outfits Nairobi",
    "engagement party outfits Kenya",
    "anniversary outfits Nairobi",
    "Valentine's Day outfits Kenya",
    "Christmas outfits Nairobi",
    "New Year's Eve outfits Kenya",
    "Easter outfits Nairobi",
    "Eid outfits Kenya",
    "Diwali outfits Nairobi",
    "birthday outfits Kenya",
    "photoshoot outfits Nairobi",
    "Instagram outfits Kenya",
    "TikTok outfits Nairobi",
    "brunch outfits Kenya",
    "lunch date outfits Nairobi",
    "dinner outfits Kenya",
    "concert outfits Nairobi",
    "music festival outfits Kenya",
    "beach outfits Nairobi",
    "pool party outfits Kenya",
    "barbecue outfits Nairobi",
    "picnic outfits Kenya",
    "travel outfits Nairobi",
    "vacation outfits Kenya",
    "safari outfits Nairobi",
    "road trip outfits Kenya",
    "airport outfits Nairobi",
    "gym outfits Kenya",
    "workout outfits Nairobi",
    "yoga outfits Kenya",
    "athleisure outfits Nairobi",
    "running errands outfits Kenya",
    "school run outfits Nairobi",
    "market day outfits Kenya",
    "shopping outfits Nairobi",
    "movie date outfits Kenya",
    "game night outfits Nairobi",
    "house party outfits Kenya",
    "housewarming outfits Nairobi",
    "family gathering outfits Kenya",
    "reunion outfits Nairobi",
    "farewell party outfits Kenya",
    "welcome party outfits Nairobi",
    "corporate event outfits Kenya",
    "networking event outfits Nairobi",
    "seminar outfits Kenya",
    "conference outfits Nairobi",
    "job interview outfits Kenya",
    "first day of work outfits Nairobi",
    "casual Friday outfits Kenya",
    "weekend outfits Nairobi",
    "weekday outfits Kenya",
    "Monday motivation outfits Nairobi",
    "work from home outfits Kenya",
    "loungewear Nairobi",
    "comfortable outfits Kenya",
    "cozy outfits Nairobi",
    "rainy day outfits Kenya",
    "cold weather outfits Nairobi",
    "hot weather outfits Kenya",
    "layered outfits Nairobi",
    "minimalist outfits Kenya",
    "maximalist outfits Nairobi",
    "monochrome outfits Kenya",
    "colorful outfits Nairobi",

    // ========== STYLE & AESTHETIC KEYWORDS (60+) ==========
    "boho style Kenya",
    "bohemian fashion Nairobi",
    "minimalist fashion Kenya",
    "classic style Nairobi",
    "vintage style Kenya",
    "retro fashion Nairobi",
    "grunge fashion Kenya",
    "punk style Nairobi",
    "preppy fashion Kenya",
    "sporty fashion Nairobi",
    "athleisure style Kenya",
    "streetwear style Nairobi",
    "urban chic Kenya",
    "casual chic Nairobi",
    "smart casual Kenya",
    "business casual Nairobi",
    "business formal Kenya",
    "cocktail attire Nairobi",
    "black tie alternative Kenya",
    "glam fashion Nairobi",
    "glamorous style Kenya",
    "edgy fashion Nairobi",
    "rocker chic Kenya",
    "romantic style Nairobi",
    "feminine fashion Kenya",
    "tomboy fashion Nairobi",
    "androgynous fashion Kenya",
    "gender neutral fashion Nairobi",
    "Afrocentric fashion Kenya",
    "African fashion Nairobi",
    "Ankara style Kenya",
    "kitenge fashion Nairobi",
    "African print fashion Kenya",
    "modern African fashion Nairobi",
    "fusion fashion Kenya",
    "East African fashion Nairobi",
    "Kenyan fashion style",
    "Nairobi fashion week style",
    "runway inspired fashion Kenya",
    "celebrity style Kenya",
    "influencer style Nairobi",
    "Y2K fashion Kenya",
    "90s fashion Nairobi",
    "80s fashion Kenya",
    "70s fashion Nairobi",
    "60s fashion Kenya",
    "old money style Nairobi",
    "quiet luxury fashion Kenya",
    "coastal grandmother style Nairobi",
    "dark academia fashion Kenya",
    "light academia fashion Nairobi",
    "cottagecore fashion Kenya",
    "fairycore fashion Nairobi",
    "coquette fashion Kenya",
    "mob wife fashion Nairobi",
    "clean girl aesthetic Kenya",
    "that girl aesthetic Nairobi",
    "Pinterest fashion Kenya",
    "Tumblr fashion Nairobi",
    "aesthetic fashion Kenya",

    // ========== DELIVERY & SHOPPING KEYWORDS (50+) ==========
    "fashion delivery Nairobi",
    "clothing delivery Kenya",
    "M-PESA fashion payment",
    "WhatsApp order Kenya",
    "order clothes online Nairobi",
    "same day delivery Nairobi",
    "next day delivery Kenya",
    "express delivery fashion Nairobi",
    "free delivery fashion Kenya",
    "affordable delivery Nairobi",
    "cash on delivery fashion Kenya",
    "COD fashion Nairobi",
    "pick up station fashion Kenya",
    "countrywide delivery fashion Kenya",
    "Nairobi CBD delivery",
    "Westlands delivery",
    "Eastlands delivery Nairobi",
    "Kilimani delivery",
    "Kileleshwa delivery",
    "Langata delivery",
    "Karen delivery",
    "South B delivery",
    "South C delivery",
    "Buruburu delivery",
    "Embakasi delivery",
    "Kasarani delivery",
    "Roysambu delivery",
    "Thika Road delivery",
    "Mombasa Road delivery",
    "Rongai delivery",
    "Kitengela delivery",
    "Thika delivery",
    "Machakos delivery",
    "Kiambu delivery",
    "Nakuru delivery",
    "Mombasa delivery",
    "Kisumu delivery",
    "Eldoret delivery",
    "online shopping Kenya",
    "online shopping Nairobi",
    "buy clothes online Kenya",
    "order fashion online Nairobi",
    "shop from home Kenya",
    "doorstep delivery fashion",
    "parcel delivery fashion Kenya",
    "courier delivery fashion Nairobi",
    "tracked delivery fashion Kenya",
    "secure delivery fashion Nairobi",
    "packaged delivery fashion Kenya",
    "fast shipping fashion Nairobi",

    // ========== PRICE & VALUE KEYWORDS (40+) ==========
    "affordable clothes Kenya",
    "cheap clothes Nairobi",
    "budget fashion Kenya",
    "low price clothing Nairobi",
    "value for money fashion Kenya",
    "best price clothes Nairobi",
    "discounted fashion Kenya",
    "sale clothes Nairobi",
    "clearance sale Kenya",
    "flash sale Nairobi",
    "deal of the day fashion Kenya",
    "weekly deals fashion Nairobi",
    "buy one get one fashion Kenya",
    "bundle deals fashion Nairobi",
    "wholesale fashion Kenya",
    "cheap but quality clothes Nairobi",
    "affordable quality fashion Kenya",
    "luxury for less Nairobi",
    "designer for less Kenya",
    "look expensive for less Nairobi",
    "under 500 clothes Kenya",
    "under 1000 clothes Nairobi",
    "under 2000 dresses Kenya",
    "under 3000 fashion Nairobi",
    "KES 500 clothes Kenya",
    "KES 1000 fashion Nairobi",
    "student budget fashion Kenya",
    "broke girl fashion Nairobi",
    "paycheck fashion Kenya",
    "salary day fashion Nairobi",
    "end month fashion deals Kenya",
    "payday deals Nairobi",
    "thrift prices Kenya",
    "mitumba prices Nairobi",
    "second hand prices Kenya",
    "preloved prices Nairobi",
    "reasonable prices fashion Kenya",
    "fair prices fashion Nairobi",
    "competitive prices fashion Kenya",
    "no minimum order fashion Nairobi",

    // ========== SEASONAL & TREND KEYWORDS (40+) ==========
    "summer fashion Kenya 2026",
    "winter fashion Nairobi 2026",
    "rainy season fashion Kenya",
    "dry season fashion Nairobi",
    "spring fashion Kenya",
    "new year new wardrobe Kenya",
    "back to school fashion Kenya",
    "festive season fashion Nairobi",
    "December fashion Kenya",
    "holiday season fashion Nairobi",
    "trending now fashion Kenya",
    "what to wear Kenya 2026",
    "fashion forecast Kenya",
    "style guide Kenya 2026",
    "wardrobe update Kenya",
    "seasonal refresh Nairobi",
    "must have fashion items Kenya",
    "essential fashion pieces Nairobi",
    "wardrobe staples Kenya",
    "timeless fashion Nairobi",
    "evergreen fashion Kenya",
    "classic pieces Nairobi",
    "investment pieces Kenya",
    "hero pieces Nairobi",
    "statement pieces Kenya",
    "conversation starter outfits Nairobi",
    "head turning outfits Kenya",
    "show stopping outfits Nairobi",
    "jaw dropping outfits Kenya",
    "fire outfits Nairobi",
    "slay outfits Kenya",
    "drip fashion Nairobi",
    "fits check Kenya",
    "outfit of the day Nairobi",
    "OOTD Kenya",
    "what I wore today Nairobi",
    "fashion inspo Kenya",
    "style inspiration Nairobi",
    "outfit ideas Kenya",
    "look book Nairobi",

    // ========== LONG-TAIL & QUESTION KEYWORDS (50+) ==========
    "where to buy thrift clothes in Nairobi",
    "best thrift shop in Nairobi 2026",
    "where to buy affordable dresses in Kenya",
    "best place to buy tops in Nairobi",
    "where to buy bodysuits in Kenya",
    "best online thrift store in Kenya",
    "where to buy quality thrift in Nairobi",
    "how to order clothes online in Kenya",
    "best fashion delivery in Nairobi",
    "where to buy jackets in Nairobi",
    "cheapest thrift shop in Nairobi",
    "most affordable fashion store Kenya",
    "trusted online clothing store Kenya",
    "reliable thrift store Nairobi",
    "best rated thrift shop Kenya",
    "top thrift stores in Nairobi",
    "popular thrift shops Kenya",
    "recommended thrift stores Nairobi",
    "thrift stores that deliver in Kenya",
    "online thrift stores with M-PESA Kenya",
    "thrift stores with WhatsApp ordering",
    "fashion stores with cash on delivery Kenya",
    "best dresses under 2000 in Nairobi",
    "best tops under 1000 in Kenya",
    "affordable bodysuits under 1500 Nairobi",
    "quality jackets under 3000 Kenya",
    "thrift dresses for wedding guests Kenya",
    "office wear thrift Nairobi",
    "date night dresses thrift Kenya",
    "party wear thrift Nairobi",
    "church dresses thrift Kenya",
    "graduation dresses affordable Nairobi",
    "birthday outfit ideas Kenya",
    "what to wear to a Kenyan wedding",
    "outfits for Nairobi weather",
    "rainy season outfits Nairobi",
    "cold morning outfits Nairobi",
    "hot afternoon outfits Nairobi",
    "Nairobi evening outfits",
    "Kenya fashion on a budget",
    "how to dress well on a budget Kenya",
    "thrift fashion tips Kenya",
    "how to thrift like a pro Nairobi",
    "best thrift finds in Kenya",
    "thrift haul Nairobi 2026",
    "Elani Beauty Hub review",
    "Elani Beauty Hub experience",
    "Elani Beauty Hub order",
    "classycollections review",
    "Elani Beauty Hub delivery review",
  ],
}

export const PAGE_SEO = {
  home: {
    title: "Elani Beauty Hub | Best Thrift & New Tops, Dresses, Bodysuits & Jackets in Nairobi Kenya",
    description:
      "Shop the best thrift and new women's tops, dresses, bodysuits, jackets, skirts and more at Elani Beauty Hub Nairobi. Kenya's #1 curated thrift and new fashion store with quality preloved and brand-new pieces at unbeatable prices. Browse 100+ styles, pay via M-PESA, and get fast delivery across Kenya. Order online or call 0702642324.",
    keywords: [
      "Elani Beauty Hub", "thrift shop Nairobi", "thrift fashion Kenya", "women tops Nairobi",
      "thrift dresses Kenya", "bodysuits Nairobi", "jackets Kenya", "affordable fashion Nairobi",
      "preloved fashion Kenya", "second hand clothes Nairobi", "mitumba fashion", "online thrift store Kenya",
      "best thrift shop Nairobi", "quality thrift Kenya", "new arrivals fashion Nairobi",
      "Elani Beauty Hub Nairobi", "beauty hub fashion", "curated thrift Kenya",
      "women fashion Nairobi", "buy clothes online Kenya", "fashion delivery Nairobi",
      "M-PESA fashion payment", "WhatsApp order Kenya", "trending fashion Kenya 2026",
    ],
  },
  shop: {
    title: "Shop All Thrift & New Fashion | Tops, Dresses, Bodysuits, Jackets, Skirts & More - Elani Beauty Hub",
    description:
      "Browse Elani Beauty Hub's full curated collection of thrift and new women's fashion. Discover affordable quality tops, dresses, bodysuits, jackets, skirts, jumpsuits, matching sets and more. Hand-picked preloved and brand-new pieces delivered across Kenya. Pay via M-PESA or cash on delivery. Best thrift shop in Nairobi.",
    keywords: [
      "shop thrift fashion Kenya", "buy clothes online Nairobi", "Elani Beauty Hub shop",
      "thrift tops Kenya", "thrift dresses Nairobi", "thrift bodysuits", "thrift jackets",
      "affordable women clothes Kenya", "curated fashion Nairobi", "online fashion store Kenya",
      "all women clothing Nairobi", "fashion catalogue Kenya", "thrift collection Nairobi",
      "new arrivals Kenya", "offers fashion Nairobi", "deals thrift Kenya",
    ],
  },
  menCollection: {
    title: "Men's Thrift & New Fashion | Shirts, Jackets, Trousers & More - Elani Beauty Hub Nairobi",
    description:
      "Shop affordable thrift and new men's fashion at Elani Beauty Hub Nairobi. Quality shirts, t-shirts, jackets, blazers, trousers, jeans, hoodies and more. Hand-picked preloved and brand-new men's clothing delivered across Kenya. Upgrade your wardrobe for less.",
    keywords: [
      "men fashion Nairobi", "men thrift Kenya", "men shirts Nairobi", "men jackets Kenya",
      "men trousers Nairobi", "men jeans Kenya", "men blazers Nairobi", "men hoodies Kenya",
      "men casual wear Nairobi", "men formal wear Kenya", "Elani Beauty Hub men",
      "affordable men clothes Kenya", "thrift men fashion Nairobi", "men preloved Kenya",
      "buy men clothes online Kenya", "men clothing delivery Nairobi",
    ],
  },
  womenCollection: {
    title: "Women's Thrift & New Tops, Dresses, Bodysuits, Jackets & Skirts | Elani Beauty Hub Nairobi",
    description:
      "Discover Elani Beauty Hub's best thrift and new women's collection. Shop quality tops, dresses, bodysuits, jackets, skirts, jumpsuits, co-ords and more. Affordable, trendy, hand-picked fashion for every occasion — office, party, casual, date night. Fast delivery across Kenya. Pay via M-PESA.",
    keywords: [
      "women fashion Nairobi", "women thrift Kenya", "women tops Nairobi", "women dresses Kenya",
      "women bodysuits Nairobi", "women jackets Kenya", "women skirts Nairobi",
      "women jumpsuits Kenya", "women co-ords Nairobi", "Elani Beauty Hub women",
      "affordable women fashion Kenya", "trendy women clothes Nairobi", "quality thrift women Kenya",
      "curated women fashion Nairobi", "women fashion delivery Kenya",
    ],
  },
  babyShop: {
    title: "Baby & Kids Thrift & New Clothes | Affordable Children's Fashion - Elani Beauty Hub Nairobi",
    description:
      "Shop affordable thrift and new baby and kids clothing at Elani Beauty Hub. Quality rompers, onesies, dresses, tops, pants, jackets and more for babies, toddlers and children. Preloved and brand-new kids fashion delivered across Kenya at the best prices.",
    keywords: [
      "baby clothes Nairobi", "kids clothes Kenya", "baby shop Nairobi", "thrift baby clothes Kenya",
      "affordable baby clothing Nairobi", "kids fashion Kenya", "baby dresses Nairobi",
      "baby rompers Kenya", "toddler clothes Nairobi", "children clothing Kenya",
      "Elani Beauty Hub baby shop", "preloved baby clothes Kenya", "kids thrift Nairobi",
      "baby clothing delivery Kenya", "cute baby clothes Nairobi",
    ],
  },
  newArrivals: {
    title: "New Arrivals | Latest Thrift & New Fashion Just Landed - Elani Beauty Hub Nairobi",
    description:
      "Shop the latest new arrivals at Elani Beauty Hub. Fresh thrift and brand-new tops, dresses, bodysuits, jackets, skirts and more just landed. Be the first to grab the newest styles at affordable prices. Updated daily with hand-picked fashion pieces. Fast delivery across Kenya.",
    keywords: [
      "new arrivals fashion Kenya", "just arrived clothes Nairobi", "latest fashion Kenya",
      "new thrift arrivals Nairobi", "fresh arrivals fashion Kenya", "new in Elani Beauty Hub",
      "latest thrift Nairobi", "trending now Kenya", "new drops fashion Nairobi",
      "weekly new arrivals Kenya", "daily new arrivals Nairobi", "what's new Elani Beauty Hub",
    ],
  },
  offers: {
    title: "Fashion Offers & Deals | Discounted Thrift & New Clothes - Elani Beauty Hub Nairobi",
    description:
      "Grab the best fashion deals and offers at Elani Beauty Hub. Discounted thrift and new tops, dresses, bodysuits, jackets and more. Limited time deals on quality preloved and brand-new women's fashion. Save big on your favourite styles. Delivery across Kenya.",
    keywords: [
      "fashion offers Kenya", "clothing deals Nairobi", "discounted fashion Kenya",
      "sale clothes Nairobi", "thrift deals Kenya", "fashion clearance Nairobi",
      "affordable deals fashion Kenya", "best offers Elani Beauty Hub", "cheap fashion Kenya",
      "budget fashion deals Nairobi", "flash sale fashion Kenya", "weekly deals Nairobi",
    ],
  },
  wishlist: {
    title: "My Wishlist | Save Your Favourite Fashion Pieces - Elani Beauty Hub",
    description:
      "Save your favourite thrift and new fashion pieces to your Elani Beauty Hub wishlist. Curate your dream collection of affordable tops, dresses, bodysuits, jackets, skirts and more. Never lose track of items you love. Shop when you're ready with easy checkout.",
    keywords: [
      "fashion wishlist Kenya", "save favourite clothes Nairobi", "Elani Beauty Hub wishlist",
      "shopping list fashion Kenya", "saved items Nairobi", "favourite pieces Kenya",
      "wish list clothes Nairobi", "bookmark fashion Kenya", "save for later fashion Nairobi",
    ],
  },
  checkout: {
    title: "Secure Checkout | Elani Beauty Hub",
    description:
      "Complete your Elani Beauty Hub order securely. Pay via M-PESA or order via WhatsApp. Affordable thrift and new women's fashion with fast delivery across Kenya.",
    noindex: true,
  },
  trackOrder: {
    title: "Track Your Order | Real-Time Delivery Updates - Elani Beauty Hub",
    description:
      "Track your Elani Beauty Hub order in real-time. Get instant delivery updates, order status, and estimated arrival time for your thrift and new fashion purchases. Reliable tracking for all orders delivered across Kenya.",
    noindex: true,
    keywords: [
      "track order Elani Beauty Hub", "order tracking Kenya", "delivery status Nairobi",
      "where is my order Kenya", "order updates Elani Beauty Hub", "delivery tracking Kenya",
      "parcel tracking Nairobi", "shipping status Kenya", "order status Elani Beauty Hub",
    ],
  },
  delivery: {
    title: "Delivery Locations & Rates | Fast Fashion Delivery Across Kenya - Elani Beauty Hub",
    description:
      "Elani Beauty Hub delivers thrift and new fashion across Kenya. Check delivery locations, affordable shipping rates, estimated delivery times and payment options. Same-day delivery available in Nairobi. Countrywide shipping to Mombasa, Kisumu, Nakuru, Eldoret and more. Pay via M-PESA or cash on delivery.",
    keywords: [
      "fashion delivery Kenya", "clothing delivery Nairobi", "shipping rates Kenya",
      "delivery locations Elani Beauty Hub", "same day delivery Nairobi", "next day delivery Kenya",
      "countrywide delivery fashion Kenya", "M-PESA payment fashion", "cash on delivery Kenya",
      "affordable shipping Kenya", "fast delivery fashion Nairobi", "Elani Beauty Hub delivery",
      "Nairobi delivery zones", "Kenya shipping fashion", "express delivery clothes Kenya",
    ],
  },
  privacyPolicy: {
    title: "Privacy Policy | Elani Beauty Hub",
    description:
      "Learn how Elani Beauty Hub collects, uses, and protects your personal information. Your privacy matters to us.",
    noindex: true,
  },
  termsOfService: {
    title: "Terms of Service | Elani Beauty Hub",
    description:
      "Review the terms and conditions for using Elani Beauty Hub. Shop thrift and new women's fashion with confidence.",
    noindex: true,
  },
  refundPolicy: {
    title: "Refund Policy | Elani Beauty Hub",
    description:
      "Learn about Elani Beauty Hub refund and return policy for thrift and new fashion purchases. Your satisfaction is our priority.",
    noindex: true,
  },
}

// Page-specific keyword sets for individual pages (used in page metadata)
export const PAGE_KEYWORDS = {
  home: [
    // Brand & Identity (50+)
    "Elani Beauty Hub", "Elani Beauty Hub Nairobi", "Elani Beauty Hub Kenya",
    "Elani Beauty Hub online store", "Elani Beauty Hub fashion", "Elani Beauty Hub thrift",
    "Elani Beauty Hub shop", "Elani Beauty Hub clothes", "Elani Beauty Hub dresses",
    "Elani Beauty Hub tops", "Elani Beauty Hub bodysuits", "Elani Beauty Hub jackets",
    "Elani online store", "Elani fashion Kenya", "Elani thrift shop", "Elani Nairobi",
    "beauty hub fashion", "beauty hub thrift", "beauty hub Nairobi", "beauty hub Kenya",
    "elanibeautyhub", "elanibeautyhub.com",
    // Thrift & Preloved (60+)
    "thrift shop Nairobi", "thrift store Kenya", "thrift clothes Nairobi",
    "thrift fashion Kenya", "best thrift shop Nairobi", "best thrift store Kenya",
    "affordable thrift Kenya", "quality thrift clothing Nairobi",
    "thrift shopping online Kenya", "online thrift store Kenya",
    "thrift finds Nairobi", "thrift haul Kenya",
    "second hand clothes Nairobi", "second hand fashion Kenya",
    "preloved fashion Nairobi", "preloved clothes Kenya",
    "mitumba fashion Kenya", "mitumba clothes Nairobi",
    "best mitumba shop Nairobi", "grade A mitumba Kenya",
    "premium mitumba Nairobi", "curated thrift Kenya",
    "sustainable fashion Kenya", "eco fashion Nairobi",
    "ex-UK clothes Nairobi", "imported thrift Kenya",
    "designer thrift Nairobi", "vintage thrift Kenya",
    "luxury thrift Kenya", "thrift boutique Kenya",
    "thrift gems Kenya", "thrift treasures Nairobi",
    "thrift steals Nairobi", "thrift bargains Kenya",
    // Products (80+)
    "women tops Nairobi", "thrift tops Kenya", "crop tops Kenya",
    "blouses Nairobi", "casual tops Nairobi", "office tops Kenya",
    "tank tops Kenya", "camisole tops Nairobi", "trendy tops Nairobi",
    "buy dresses online Kenya", "women dresses Nairobi", "thrift dresses Kenya",
    "maxi dresses Nairobi", "mini dresses Kenya", "bodycon dresses Nairobi",
    "party dresses Nairobi", "cocktail dresses Kenya", "office dresses Kenya",
    "sundresses Nairobi", "floral dresses Nairobi", "lace dresses Kenya",
    "buy bodysuits online Kenya", "women bodysuits Nairobi", "thrift bodysuits Kenya",
    "mesh bodysuits Kenya", "lace bodysuits Kenya", "long sleeve bodysuits Kenya",
    "buy jackets online Kenya", "women jackets Nairobi", "thrift jackets Kenya",
    "denim jackets Nairobi", "leather jackets Kenya", "bomber jackets Nairobi",
    "blazers Kenya", "cropped jackets Nairobi", "puffer jackets Kenya",
    "buy skirts online Kenya", "women skirts Nairobi", "thrift skirts Kenya",
    "mini skirts Nairobi", "midi skirts Kenya", "maxi skirts Nairobi",
    "pencil skirts Kenya", "pleated skirts Kenya",
    "jumpsuits Kenya", "rompers Nairobi", "matching sets Kenya", "co-ord sets Nairobi",
    // General Fashion (60+)
    "women fashion Nairobi", "women fashion Kenya", "affordable fashion Kenya",
    "quality fashion Nairobi", "trendy fashion Kenya",
    "buy women clothing online Kenya", "online fashion store Kenya",
    "Nairobi fashion boutique", "Kenyan fashion brands",
    "fashion trends Kenya 2026", "best online clothing store Kenya",
    "new and thrift fashion Kenya", "curated fashion Nairobi",
    "ladies fashion Kenya", "girls fashion Nairobi",
    "budget fashion Kenya", "value fashion Nairobi",
    "latest fashion Nairobi", "trending fashion Kenya",
    "TikTok fashion Kenya", "Instagram fashion Nairobi",
    "street style Kenya", "Nairobi street fashion",
    "urban fashion Kenya", "campus fashion Kenya",
    "plus size fashion Kenya", "inclusive fashion Kenya",
    // Occasions (50+)
    "date night outfits Kenya", "office wear women Kenya",
    "wedding guest outfits Kenya", "graduation outfits Kenya",
    "church outfits women Nairobi", "party wear Kenya",
    "casual women wear Kenya", "professional women wear Nairobi",
    "formal wear women Kenya", "streetwear women Kenya",
    "birthday outfits Kenya", "brunch outfits Kenya",
    "vacation outfits Kenya", "festival outfits Nairobi",
    "baby shower outfits Nairobi", "photoshoot outfits Nairobi",
    "concert outfits Nairobi", "dinner outfits Kenya",
    "work outfits Nairobi", "weekend outfits Nairobi",
    // Style Aesthetics (40+)
    "boho style Kenya", "minimalist fashion Kenya",
    "classic style Nairobi", "vintage style Kenya",
    "smart casual Kenya", "business casual Nairobi",
    "Afrocentric fashion Kenya", "African fashion Nairobi",
    "Y2K fashion Kenya", "old money style Nairobi",
    "clean girl aesthetic Kenya", "Pinterest fashion Kenya",
    "coquette fashion Kenya", "dark academia fashion Kenya",
    // Delivery & Shopping (40+)
    "fashion delivery Nairobi", "clothing delivery Kenya",
    "M-PESA fashion payment", "WhatsApp order Kenya",
    "order clothes online Nairobi", "same day delivery Nairobi",
    "cash on delivery fashion Kenya", "free delivery fashion Kenya",
    "online shopping Kenya", "buy clothes online Kenya",
    "countrywide delivery fashion Kenya", "fast shipping fashion Nairobi",
    // Pricing (30+)
    "affordable clothes Kenya", "cheap clothes Nairobi",
    "budget fashion Kenya", "best price clothes Nairobi",
    "under 1000 clothes Nairobi", "under 2000 dresses Kenya",
    "student budget fashion Kenya", "thrift prices Kenya",
    "reasonable prices fashion Kenya", "luxury for less Nairobi",
    // Long-tail (40+)
    "where to buy thrift clothes in Nairobi",
    "best thrift shop in Nairobi 2026",
    "where to buy affordable dresses in Kenya",
    "best place to buy tops in Nairobi",
    "best online thrift store in Kenya",
    "how to order clothes online in Kenya",
    "thrift stores that deliver in Kenya",
    "best dresses under 2000 in Nairobi",
    "outfits for Nairobi weather",
    "Elani Beauty Hub review",
    // Men (30+)
    "men fashion Nairobi", "men thrift Kenya", "men shirts Nairobi",
    "men jackets Kenya", "men trousers Nairobi", "men jeans Kenya",
    "buy men clothes online Kenya", "men clothing delivery Kenya",
    "men formal wear Kenya", "men casual wear Nairobi",
    // Baby & Kids (20+)
    "baby clothes Kenya", "kids clothes Nairobi", "baby shop Nairobi",
    "thrift baby clothes Kenya", "kids fashion Kenya",
    "affordable baby clothes Kenya", "baby dresses Nairobi",
    "toddler clothes Nairobi", "preloved baby clothes Kenya",
    // Seasonal (20+)
    "fashion trends Kenya 2026", "new year new wardrobe Kenya",
    "festive season fashion Nairobi", "trending now fashion Kenya",
    "wardrobe essentials Kenya", "capsule wardrobe Nairobi",
    "OOTD Kenya", "outfit ideas Kenya", "style inspiration Nairobi",
    "fashion inspo Kenya", "look book Nairobi",
  ],

  shop: [
    "Elani Beauty Hub shop", "shop all fashion Nairobi", "browse clothes online Kenya",
    "thrift shop online Kenya", "fashion catalogue Nairobi", "all women clothing Kenya",
    "thrift collection Nairobi", "new arrivals Kenya", "fashion deals Nairobi",
    "curated fashion Kenya", "hand-picked fashion Nairobi", "quality thrift Kenya",
    "affordable fashion Nairobi", "trendy clothes Kenya", "stylish fashion Nairobi",
    "latest fashion Kenya", "best sellers Nairobi", "popular items Kenya",
    "top rated fashion Nairobi", "customer favourites Kenya",
    "tops collection Nairobi", "dresses collection Kenya", "bodysuits collection Nairobi",
    "jackets collection Kenya", "skirts collection Nairobi", "jumpsuits collection Kenya",
    "sets collection Nairobi", "pants collection Kenya",
    "thrift tops Nairobi", "thrift dresses Kenya", "thrift bodysuits Nairobi",
    "thrift jackets Kenya", "thrift skirts Nairobi", "thrift jumpsuits Kenya",
    "new tops Nairobi", "new dresses Kenya", "new bodysuits Nairobi",
    "new jackets Kenya", "new skirts Nairobi",
    "shop by category Kenya", "shop by style Nairobi", "shop by occasion Kenya",
    "shop by price Nairobi", "filter fashion Kenya", "sort by newest Nairobi",
    "sort by price Kenya", "shop all sizes Nairobi", "shop all colours Kenya",
    "women fashion store Kenya", "online boutique Nairobi", "fashion marketplace Kenya",
    "buy now pay later fashion Kenya", "M-PESA shopping Nairobi",
    "WhatsApp order fashion Kenya", "cash on delivery clothes Nairobi",
    "free delivery fashion Kenya", "same day delivery Nairobi",
    "quality guaranteed fashion Kenya", "trusted online store Nairobi",
    "verified seller fashion Kenya", "authentic fashion Nairobi",
    "original clothes Kenya", "branded fashion Nairobi",
    "size XS fashion Kenya", "size S fashion Nairobi", "size M fashion Kenya",
    "size L fashion Nairobi", "size XL fashion Kenya", "size XXL fashion Nairobi",
    "plus size fashion Kenya", "petite fashion Nairobi",
    "under 500 fashion Kenya", "under 1000 fashion Nairobi",
    "under 2000 fashion Kenya", "under 5000 fashion Nairobi",
    "budget fashion Kenya", "mid-range fashion Nairobi", "premium fashion Kenya",
  ],

  menCollection: [
    "men fashion Nairobi", "men clothing Kenya", "thrift men clothes Nairobi",
    "men shirts Kenya", "men t-shirts Nairobi", "polo shirts men Kenya",
    "button up shirts men Nairobi", "dress shirts men Kenya", "casual shirts men Nairobi",
    "Hawaiian shirts men Kenya", "flannel shirts men Nairobi",
    "men jackets Nairobi", "thrift jackets men Kenya", "men blazers Nairobi",
    "men suits Kenya", "men trousers Nairobi", "men jeans Kenya",
    "men chinos Nairobi", "men khakis Kenya", "men shorts Nairobi",
    "men cargo pants Kenya", "men joggers Nairobi", "men sweatshirts Kenya",
    "men hoodies Nairobi", "men sweaters Kenya", "men cardigans Nairobi",
    "men formal wear Nairobi", "men casual wear Kenya", "men office wear Nairobi",
    "men streetwear Kenya", "affordable men clothing Nairobi",
    "quality men thrift Kenya", "men wardrobe essentials Kenya",
    "men outfits Kenya", "men style Nairobi",
    "men denim jacket Nairobi", "men leather jacket Kenya",
    "men bomber jacket Nairobi", "men puffer jacket Kenya",
    "men smart casual Nairobi", "men wedding outfits Kenya",
    "men graduation outfits Nairobi", "men church outfits Kenya",
    "Elani Beauty Hub men", "men thrift Nairobi best",
    "men preloved clothes Kenya", "men second hand fashion Nairobi",
    "men mitumba Kenya", "men designer thrift Nairobi",
    "buy men clothes online Kenya", "men clothing delivery Kenya",
    "men athleisure Nairobi", "men workwear Kenya",
    "men track suit Nairobi", "men sportswear Kenya",
    "men vintage fashion Nairobi", "men classic style Kenya",
    "men urban fashion Nairobi", "men modern fashion Kenya",
    "men trendy clothes Nairobi", "men fashionable clothing Kenya",
  ],

  womenCollection: [
    "women fashion Nairobi", "women clothing Kenya", "thrift women clothes Nairobi",
    "women tops Nairobi", "women dresses Kenya", "women bodysuits Nairobi",
    "women jackets Kenya", "women skirts Nairobi", "women jumpsuits Kenya",
    "women co-ords Nairobi", "women pants Kenya", "women blouses Nairobi",
    "women crop tops Kenya", "women maxi dresses Nairobi", "women mini dresses Kenya",
    "women bodycon dresses Nairobi", "women casual dresses Kenya",
    "women party dresses Nairobi", "women office dresses Kenya",
    "women blazers Nairobi", "women cardigans Kenya",
    "women formal wear Nairobi", "women casual wear Kenya",
    "women office wear Nairobi", "women streetwear Kenya",
    "affordable women clothing Nairobi", "quality women thrift Kenya",
    "women wardrobe essentials Kenya", "women outfits Nairobi",
    "women style Kenya", "Elani Beauty Hub women",
    "women thrift Nairobi best", "women preloved clothes Kenya",
    "curated women fashion Nairobi", "hand-picked women fashion Kenya",
    "trendy women clothes Nairobi", "stylish women fashion Kenya",
    "elegant women fashion Nairobi", "classy women clothes Kenya",
    "chic women fashion Nairobi", "cute women clothes Kenya",
    "sexy women fashion Nairobi", "modest women fashion Kenya",
    "plus size women fashion Nairobi", "petite women fashion Kenya",
    "women fashion delivery Nairobi", "buy women clothes online Kenya",
    "women M-PESA fashion Kenya", "women WhatsApp order Nairobi",
    "women date night fashion Kenya", "women office fashion Nairobi",
    "women wedding guest fashion Kenya", "women graduation fashion Nairobi",
    "women church fashion Kenya", "women party fashion Nairobi",
    "women birthday fashion Kenya", "women brunch fashion Nairobi",
    "women vacation fashion Kenya", "women festival fashion Nairobi",
    "women weekend fashion Kenya", "women everyday fashion Nairobi",
  ],

  babyShop: [
    "baby clothes Kenya", "kids clothes Nairobi", "baby shop Nairobi",
    "thrift baby clothes Kenya", "thrift kids clothes Nairobi",
    "affordable baby clothes Kenya", "baby dresses Nairobi",
    "baby rompers Kenya", "baby onesies Nairobi", "baby bodysuits Kenya",
    "baby tops Nairobi", "baby pants Kenya", "baby jackets Nairobi",
    "toddler clothes Nairobi", "kids fashion Kenya", "children clothing Nairobi",
    "boys clothes Kenya", "girls clothes Nairobi", "girls dresses Kenya",
    "boys shirts Nairobi", "kids thrift Kenya", "baby thrift Nairobi",
    "preloved baby clothes Kenya", "second hand kids clothes Nairobi",
    "baby mitumba Kenya", "kids mitumba Nairobi",
    "baby clothing deals Kenya", "affordable kids fashion Nairobi",
    "cute baby clothes Kenya", "baby outfit sets Nairobi",
    "kids matching sets Kenya", "baby essentials Nairobi",
    "newborn clothes Kenya", "infant clothes Nairobi",
    "Elani Beauty Hub baby shop", "baby delivery Kenya",
    "kids clothes delivery Nairobi", "baby clothes online Kenya",
    "buy kids clothes online Nairobi", "children fashion delivery Kenya",
  ],

  newArrivals: [
    "new arrivals fashion Kenya", "just arrived clothes Nairobi",
    "latest fashion Kenya", "new thrift arrivals Nairobi",
    "fresh arrivals fashion Kenya", "new in Elani Beauty Hub",
    "latest thrift Nairobi", "trending now Kenya",
    "new drops fashion Nairobi", "weekly new arrivals Kenya",
    "daily new arrivals Nairobi", "what's new Elani Beauty Hub",
    "just landed fashion Kenya", "freshly curated Nairobi",
    "new collection Elani Beauty Hub", "new stock Kenya",
    "restocked fashion Nairobi", "back in stock Kenya",
    "limited edition fashion Nairobi", "exclusive arrivals Kenya",
    "first dibs fashion Nairobi", "be the first Kenya",
    "new tops Nairobi", "new dresses Kenya", "new bodysuits Nairobi",
    "new jackets Kenya", "new skirts Nairobi", "new jumpsuits Kenya",
    "new thrift tops Nairobi", "new thrift dresses Kenya",
    "trending fashion 2026 Kenya", "fashion forecast Nairobi",
    "must have items Kenya", "essential pieces Nairobi",
    "statement pieces Kenya", "hero pieces Nairobi",
  ],

  offers: [
    "fashion offers Kenya", "clothing deals Nairobi", "discounted fashion Kenya",
    "sale clothes Nairobi", "thrift deals Kenya", "fashion clearance Nairobi",
    "affordable deals fashion Kenya", "best offers Elani Beauty Hub",
    "cheap fashion Kenya", "budget fashion deals Nairobi",
    "flash sale fashion Kenya", "weekly deals Nairobi",
    "deal of the day fashion Kenya", "limited time offers Nairobi",
    "buy one get one Kenya", "bundle deals fashion Nairobi",
    "clearance sale Kenya", "end of season sale Nairobi",
    "mega sale fashion Kenya", "discount code Elani Beauty Hub",
    "promo code fashion Kenya", "special offer Nairobi",
    "save money fashion Kenya", "value deals Nairobi",
    "under 500 deals Kenya", "under 1000 deals Nairobi",
    "half price fashion Kenya", "reduced price Nairobi",
    "markdown fashion Kenya", "last chance deals Nairobi",
    "going fast fashion Kenya", "selling out Nairobi",
    "final sale fashion Kenya", "no minimum order Nairobi",
  ],

  delivery: [
    "fashion delivery Kenya", "clothing delivery Nairobi", "shipping rates Kenya",
    "delivery locations Elani Beauty Hub", "same day delivery Nairobi",
    "next day delivery Kenya", "express delivery fashion Nairobi",
    "countrywide delivery fashion Kenya", "M-PESA payment fashion",
    "cash on delivery Kenya", "affordable shipping Kenya",
    "fast delivery fashion Nairobi", "Elani Beauty Hub delivery",
    "Nairobi delivery zones", "Kenya shipping fashion",
    "Nairobi CBD delivery", "Westlands delivery", "Kilimani delivery",
    "Kileleshwa delivery", "Langata delivery", "Karen delivery",
    "South B delivery", "South C delivery", "Buruburu delivery",
    "Embakasi delivery", "Kasarani delivery", "Roysambu delivery",
    "Thika Road delivery", "Mombasa Road delivery",
    "Rongai delivery", "Kitengela delivery", "Thika delivery",
    "Machakos delivery", "Kiambu delivery", "Nakuru delivery",
    "Mombasa delivery", "Kisumu delivery", "Eldoret delivery",
    "tracked delivery fashion Kenya", "secure delivery fashion Nairobi",
    "doorstep delivery fashion Kenya", "pick up station fashion Kenya",
    "delivery charges Kenya", "shipping cost fashion Nairobi",
    "how long delivery Kenya", "delivery time fashion Nairobi",
    "order tracking Kenya", "parcel tracking Nairobi",
    "reliable delivery Kenya", "trusted shipping Nairobi",
  ],

  wishlist: [
    "fashion wishlist Kenya", "save favourite clothes Nairobi",
    "Elani Beauty Hub wishlist", "shopping list fashion Kenya",
    "saved items Nairobi", "favourite pieces Kenya",
    "wish list clothes Nairobi", "bookmark fashion Kenya",
    "save for later fashion Nairobi", "curate collection Kenya",
    "dream wardrobe Nairobi", "fashion bookmarks Kenya",
    "liked items Nairobi", "heart fashion Kenya",
    "must have list Nairobi", "shopping cart Kenya",
  ],

  trackOrder: [
    "track order Elani Beauty Hub", "order tracking Kenya",
    "delivery status Nairobi", "where is my order Kenya",
    "order updates Elani Beauty Hub", "delivery tracking Kenya",
    "parcel tracking Nairobi", "shipping status Kenya",
    "order status Elani Beauty Hub", "real time tracking Kenya",
    "live tracking fashion Nairobi", "delivery ETA Kenya",
    "estimated delivery time Nairobi", "order confirmation Kenya",
    "dispatch notification Nairobi", "out for delivery Kenya",
  ],
}

export function generateProductKeywords(productName: string, category: string, tags: string[] = []): string[] {
  const baseKeywords = [
    productName,
    `buy ${productName} online Kenya`,
    `${productName} Nairobi`,
    `${productName} Kenya`,
    `thrift ${productName}`,
    `affordable ${productName} Kenya`,
    "Elani Beauty Hub",
    "Elani Beauty Hub Nairobi",
    "Elani Beauty Hub Kenya",
    "thrift fashion Kenya",
    "buy online Kenya",
    category || "women fashion",
    `thrift ${category} Kenya`,
    `thrift ${category} Nairobi`,
    `affordable ${category} Kenya`,
    `buy ${category} online Kenya`,
    `${category} Nairobi`,
    ...tags,
    "affordable fashion Nairobi",
    "quality thrift clothing",
    "new and thrift Kenya",
    "best thrift shop Nairobi",
    "preloved fashion Kenya",
    "second hand fashion Nairobi",
    "mitumba fashion Kenya",
    "online fashion store Kenya",
    "fashion delivery Nairobi",
    "M-PESA fashion payment",
    "WhatsApp order Kenya",
    "cash on delivery fashion Kenya",
    "women fashion Nairobi",
    "Kenyan fashion",
    "Nairobi boutique",
    "sustainable fashion Kenya",
    "curated fashion Nairobi",
  ]
  return [...new Set(baseKeywords.filter(Boolean))]
}
